### ISSUE TITLE
Validate patch file when no changes are present in diff.

### ISSUE THREAD

**Issue by andrueastman** [baywet/kiota-dom-export-diff-tool#6]
Creating this issue for further investigation.

Taking a look at the latest run of the tool at https://github.com/microsoftgraph/msgraph-sdk-dotnet/actions/runs/10791027467/job/29927536428?pr=2665

Similar to java run at https://github.com/microsoftgraph/msgraph-sdk-java/actions/runs/10790861308?pr=2152

The explanations look to be too large given no dom changes. (export file is unchanged and not in diff)

At first glance at the artifacts, it looks like the export stage is evaluating the file as if it new from the given patch file. This is probably an issue with the https://github.com/microsoftgraph/kiota-dom-export-diff-tool/blob/main/export/generateDomPatch.ps1 that needs to be validated.

**Comment by baywet** [comment]
thanks for creating this.
Looking at the java pull request https://github.com/microsoftgraph/msgraph-sdk-java/pull/2152 it seems we have only doc comment changes. Which would concur with your initial hypothesis.
